#!/bin/csh


#******************************************************#
#                                                      #
#           Script for extracting various              #
#        information from molpro output files          #
#                                                      #
#        Benjamin Jackson, Auburn University           #
#                 baj0040@auburn.edu                   #
#                                                      #
#                 Updated: 9/16/2019                   #
#                                                      #
#******************************************************#


# Usage and Variable Check
 if ( $#argv < 1 ) then
   echo "Usage:" $0 "filename, search type (m:MCSCF, c:MRCI, q:mrci+q, rcc:RHF-CC, r:CASPT2, d:Distances,lz[irrep1-8])"
   exit 1
 else if ( $#argv < 2 ) then
   echo "Not all parameters are given"
   exit 1
 endif

# Variables
 set file = $1
 set stype = $2
 
# Search Check
 if ($stype == m) then
  grep 'MCSCF STATE.... Energy' $1 | awk '{print $NF}' 
 else if ($stype == c) then
  grep 'MRCI STATE.... Energy' $1 | awk '{print $NF}'
 else if ($stype == q) then
  grep '(Davidson, rotated reference)' $1 | awk '{print $4}' | awk 'NR%2==0'
 else if ($stype == q2) then
  grep '(Davidson, relaxed reference)' $1 | awk '{print $4}' 
 else if ($stype == rcc) then
  grep 'RHF-RCCSD(T)' $1 | awk '{print $3}'
 else if($stype == r) then
  grep 'RSPT2 STATE' $1 | awk '{print $5}'
 else if ($stype == d) then
  grep 'SETTING RT([0-9]*)' $1 | awk '{print $4}'
 else if ($stype == lz) then
  echo "$1"
  grep '|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz1) then
  echo "$1"
  grep '.1|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz2) then
   echo "$1"
  grep '.2|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz3) then
  echo "$1"
  grep '.3|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz4) then
  echo "$1"
  grep '.4|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz5) then
  echo "$1"
  grep '.5|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz6) then
  echo "$1"
  grep '.6|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz7) then
  echo "$1"
  grep '.7|LZLZ' $1 | awk '{print $3,$4}'
 else if ($stype == lz8) then
  echo "$1"
  grep '.8|LZLZ' $1 | awk '{print $3,$4}'
 else 
  echo "Error: incorrect search specification"
 endif 
