#!/bin/bash

#******************************************************#
#                                                      #
#                         MF2                          #
#           Script for extracting various              #
#        information from molpro output files          #
#                                                      #
#        Benjamin Jackson, Auburn University           #
#                 baj0040@auburn.edu                   #
#                                                      #
#                 Updated: 9/16/2019                   #
#                                                      #
#******************************************************#


Main(){

##Changeable Variables:
	DIS_VAR=RT
##
if [[ $1 == *.out* ]]; then 
	FNAME=$1; STYPE=$2; else FNAME=$2; STYPE=$1; 
fi
while getopts ":h" option; do
	case $option in
		h) Helpfn; exit;;
		\?) Search_Fn; break;;
	esac
done
if [[ "$#" -lt "1" ]]; then Helpfn; else Search_Fn; fi;
}
Search_Fn(){
	DIS_FIX=$( echo ${DIS_VAR} | awk '{print toupper($1)}')
case ${STYPE} in
	m) grep 'MCSCF STATE [a-zA-Z0-9. ]* Energy' ${FNAME} | awk '{print $NF}';;
	c) grep 'MRCI STATE [a-zA-Z0-9. ]* Energy' ${FNAME} | awk '{print $NF}';;
	q) grep '(Davidson, fixed reference)' ${FNAME} | awk '{print $4}' ;;#| awk 'NR%2==0';;
	q2) grep '(Davidson, relaxed reference)' ${FNAME} | awk '{print $4}';;
	pt2) grep 'RSPT2 STATE' ${FNAME} | awk '{print $5}';;
	rhf) grep '!RHF' ${FNAME} | awk '{print $NF}';;
	uhf) grep '!UHF' ${FNAME} | awk '{print $NF}';;
	ump2)  grep '!UMP2' ${FNAME} | awk '{print $NF}';;
	rmp2) grep '!RMP2 [a-zA-Z0-9. ]* total energy' ${FNAME} | awk '{print $NF}';;
	rcc) grep 'RHF-RCCSD(T)' ${FNAME} | awk '{print $3}';;
	ci) grep '!CI(SD) [a-zA-Z0-9. ]* Energy' ${FNAME} | awk '{print $5}';;
	cisd) grep '!RHF-UCISD energy' ${FNAME} | awk '{print $3}';;
	d) grep "SETTING ${DIS_FIX}([0-9]*)" ${FNAME} | awk '{print $4}';;
	*) echo "Error: Incorrect search specification"
esac
}

Helpfn(){
echo "
MF2 script
Used for pulling various data from molpro out files
      Search Options:
       m     |   Search for MCSCF Energies
       c     |   Search for MRCI Energies
       q     |   Search for Davidson Corrected MRCI+Q Energies (Rotated)
       q2    |   Search for Davidson Corrected MRCI+Q Energies (Relaxed)
       pt2   |   Search for CASSCF/RSPT2 Energies
       rhf   |   Search for RHF Energies
       uhf   |   Search for UHF Energies
       ump2  |   Search for UMP2 Energies
       rmp2  |   Search for RMP2 Energies
       rcc   |   Search for RHF-RCCSD(T) Energies
       ci    |   Search for CISD Energies (CI Program)
       cisd  |   Search for CISD Energies (CISD Program)
       d     |   Search for distances used in a scan, see below 

Only one search may be performed at a time. The search type and file name may be placed in any order

Distances search look for a default value which is the name of the table used in the do loop
Your current default value is:
       Distance Variable   =   ${DIS_VAR}
You can change this in $(echo $0)

This help menu is viewable again by running this script without inputs or with the -h flag
EXAMPLE:
$(echo $0) File_name.com m
or
$(echo $0) m file_name.com 
"
}

Main "$@"; exit
